### ISSUE TITLE
Incorrect day calculation and missing some license type..

### ISSUE THREAD

**Issue by Deltafox79** [DoubleLabyrinth/010Editor-keygen#2]
Hi mr DoubleLabyrinth
I noticed two issue : 

1) that the calculation of the days is not accurate always has two days of difference with that calculated by the software .. I have fix this fast :

std::tm ExpireDate = { 0, 0, 0, ExpireDay + 2, ExpireMonth, ExpireYear - 1900 };

2) I believe that in the key calculation there is no possibility to set the site license:
we have:
> 
> Single-User -> LicenseCount = 1
> Multi-user -> **here can be set the number of user**  up to 999 your **LicenseCount**
> Site -> ?

Example : 

Expire date set to  **08/Feb/2106** :
Usename = DeltaFoX

Single-User = FA1D-73AC-E41B-7B83-3D8E
Multi-User (**5**) = 9771-29AC-BF5D-16EF-66C8
Site = **B145-2EAC-7A15-30EC-A380**

Regards

**Comment by DoubleLabyrinth** [comment]
@Deltafox79 
Thanks for your feedback.

__For the 1st issue:__
I just did some research, and found that both of us made a mistake. The `tm_mon` member in struct `std::tm` is defined as `months since January` according to [www.cplusplus.com](http://www.cplusplus.com/reference/ctime/tm/). That means __0__ is for __January__. So `ExpireDate` shall be 
```cpp
std::tm ExpireDate = { 0, 0, 0, ExpireDay, ExpireMonth - 1, ExpireYear - 1900 };
```
And the calculation towards `ExpireDaystamp` can be simplified to
```cpp
uint32_t ExpireDaystamp = std::mktime(&ExpireDate) / 3600 / 24;
```
Of course, we shall assert that `sizeof(time_t)` is 8 if `ExpireDate` is larger than __January 19, 2038__ and `ExpireDate` is a valid date so that `std::mktime(&ExpireDate)` will not return __-1__. We don't need `ZeroDate` any more.

__For the 2nd issue:__
It can be site license if and only if `LicenseCount = 1000`.

![capture](https://user-images.githubusercontent.com/16631994/42134490-572360ee-7d6f-11e8-966f-ec0dfb921f87.PNG)

Here is the related code. It seems for initial version of 010Editor `LicenseCount >= 50` can be site license.
But after that only `LicenseCount >= 1000` can be site license. However 010Editor do not accept `LicenseCount > 1000`. So only `License = 1000` is ok.

**Comment by Deltafox79** [comment]
Thank I upgrade Gui version soon.. Regards
