### ISSUE TITLE
Tried server.py,  gave error

### ISSUE THREAD

**Issue by abdulbadii** [DoubleLabyrinth/010Editor-keygen#5]
I tried server.py on Msys terminal but gave error
```
$ python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from http.server import HTTPServer, BaseHTTPRequestHandler
ImportError: No module named http.server
```
How to solve it?

**Comment by DoubleLabyrinth** [comment]
Run in python3, not python2.

**Comment by abdulbadii** [comment]
`$ python3 server.py`

seemed as if "hanging" ie. not processing anything..

**Comment by DoubleLabyrinth** [comment]
Well, `server.py` is just a simple http server and is used to bypass online check which happens when you click `activate` button in 010Editor.

You should 
1. redirect `www.sweetscape.com` to `127.0.0.1` by modifying `hosts`.
2. `$ python3 server.py`
3. Goto 010Editor and use the key generated by `010Editor-keygen.exe` to activate.
4. If fail, you can re-try several times. If succeed, have fun and `Ctrl + C` to close `server.py`.

**Comment by abdulbadii** [comment]
Ace hit !
Thanks so much... just didn't get, that must be run simultaneously with 010Editor.exe
